dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: "bookstoremanager"
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache