dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: "bookstoremanager"
script:
  - mvn clean package sonar:sonar -P sonar
  # Put before sonar-scanner your other script steps
  - sonar-scanner -Dsonar.verbose=true -X
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache